package org.teachfx.antlr4.ep21.pass.codegen;

import org.teachfx.antlr4.ep21.ir.IRNode;
import org.teachfx.antlr4.ep21.ir.Prog;

import java.util.List;
import java.util.Map;

/**
 * Unified code generator interface for VM targets.
 * This interface abstracts code generation for different VM targets (StackVM, RegisterVM).
 */
public interface ICodeGenerator {

    /**
     * Generates bytecode for the given program.
     *
     * @param program the IR program to generate code for
     * @return the result containing generated bytecode and metadata
     */
    CodeGenerationResult generate(Prog program);

    /**
     * Generates bytecode for a list of IR nodes (basic block level).
     *
     * @param instructions the IR instructions to generate code for
     * @return the result containing generated bytecode and metadata
     */
    CodeGenerationResult generateFromInstructions(List<IRNode> instructions);

    /**
     * Returns the target VM type this generator supports.
     *
     * @return the target VM type identifier ("EP18" or "EP18R")
     */
    String getTargetVM();

    /**
     * Initializes the generator with configuration options.
     *
     * @param config configuration options for code generation
     */
    default void configure(Map<String, Object> config) {
        // Default empty implementation
    }

    /**
     * Gets the emitter used by this generator.
     *
     * @return the instruction emitter
     */
    IEmitter getEmitter();
}
